sudo: required
services:
  - docker

before_install:
  - docker build -t injectit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run injectit/react-test npm test -- --coverage

after_success:
  - docker build -t injectit/multi-client ./client
  - docker build -t injectit/multi-nginx ./nginx
  - docker build -t injectit/multi-server ./server
  - docker build -t injectit/multi-worker ./worker
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to hub.docker.com
